### ISSUE TITLE
Sometimes not work on Firefox for Android

### ISSUE THREAD

**Issue by lingex** [Dosx001/YouTubeUtils#5] opened 2024-04-14 14:06 UTC
Sometimes it doesn't work; when it fails, the loop playback button remains visible, even on the homepage, but it's unresponsive when clicked. Refreshing the page once can make it work again, but after watching a few videos, at some point, it stops working again.

**Comment by Dosx001** [comment] 2024-04-21 19:43
Hey sorry about the late response. I've been aware of this issue for a long time. I currently don't have a solution for this. I will need to do a debugging session for the mobile version. However, I'm currently busy with other projects so I won't be fixing this anytime soon.

**Comment by Dosx001** [comment] 2024-05-08 23:54
So I had some free time and I started debugging. But the extension to my surprise started working flawlessly... It would be nice if there were documented situations where the extension fails consistently. Then I will be able to fix it. Until then I'm shooting blind here.

Include everything in a report like how you opened the tab and with what URL to what are your user settings.

**Comment by lingex** [comment] 2024-05-09 04:36
Alright, let's try to find the issue.

I've just conducted some careful testing and may have found a way to reproduce the problem:
1. Refresh the YouTube homepage and scroll up and down to check if the add-on is working (the loop playback button in the top-left corner is not displayed).
2. Click on a video to go to the playback page. Here, the quality option can be locked to the desired setting. Wait for the playback to finish. After completion, the playback menu and loop playback button will both appear.
3. Hit the back button to return to the homepage and scroll up and down to observe. At this point, you'll notice that the loop playback button in the top-left corner remains visible (this indicates the add-on is not working).
4. Click on a video to go to the playback page again. Now, the loop playback button in the top-left corner continues to be visible, and the quality option is set to 'auto'. If YouTube thinks the network quality is poor, it may continuously lower the quality setting.
5. When the loop playback button in the top-left corner remains visible, refreshing the page once, whether on the homepage or the playback page, will make it disappear (the add-on returns to working).

**Comment by lingex** [comment] 2024-05-09 05:28
6. In step 2, if you click the back button before the playback ends, the loop playback button will not appear (the add-on will not fail)!

**Comment by lingex** [comment] 2024-05-11 14:09
I've tried that if I keep using "Open link in new tab," it won't stop working, but sometimes this is inconvenient.

**Comment by Dosx001** [comment] 2024-05-11 21:33
`Open link in new tab` and open from external apps works for me minus the replay button not appearing. Resolution, playback speed, subtitles, and all.

**Comment by Dosx001** [comment] 2024-06-03 02:01
@lingex So I'm still having trouble consistently reproducing this bug. Maybe you could make a video of the example you wrote about?

However, I did think of an easy workaround. I added a button to reload the extension. It seems to work perfectly. The button loads outside the YouTube UI so it will always appear, unlike the loop button.
![Screenshot_20240602-184501](https://github.com/Dosx001/YouTubeUtils/assets/62494922/6adb800e-37b4-48d7-b278-18c5ef924230)

I also thought why not build a UI on top of this to change settings more easily. I could easily do this and close #4 @shalva97

**Comment by lingex** [comment] 2024-06-08 02:18
@Dosx001 Sure, I recorded a screen video where you can see that the "loop playback" button keeps showing all the time, and neither the playback speed nor the quality settings work after the first video finishes playing.

https://github.com/Dosx001/YouTubeUtils/assets/13662998/eb8aa0bf-ae5e-4caf-b6de-2d5fae24a16c

**Closed as completed** 2024-06-16 18:28 UTC
Labels: bug

**Comment by Dosx001** [comment] 2024-06-16 18:30
@lingex i believe I fixed the bug. I pushed the update. Check it out. Thanks for the video. If there are any more bugs please report.
